---
title: "Tatort Restschuld"
author: "Frank"
date: 2025-05-14
categories: [Tatort, ARD, Krimi, Serie, Deutsch]
---

# Tatort Restschuld - Team Köln

Alt und ranzig - es gibt einfach nichts mehr, was Ballauf und Schenk verbindet. Grummelnd eiern sie durch den neuen Tatort. Ballauf zu reich, zu wenig sensibel für die monetären Sorgen der Geringverdiener. Schenk als Anwalt der Verschuldeten. Naja, wenigsten keine mißhandelten Kinder oder Ausländer. Dunkel und schwer, in Moll, nimmt uns das Team Köln mit durch die Nacht, in die Leben der Verschuldeten. Abbezahlen scheint keine wirksame Lösung, also wird nach einem eher lethalen Ausweg gesucht - lethal für den Schuldeneintreiber. Und man braucht Durchhaltekraft. Verschiedene Verdächtige, Motive, Möglichkeiten und doch keine Lösung in Sicht. Der möglicherweise noch lebende Entführte wird einfach nicht gefunden. 

Wer achtzig Minuten dran bleibt, der bekommt in den letzten Minuten des Tatorts eine (überraschende?) Wendung serviert. Alles nur ein bedauerlicher Unfall. Und der Verursacher wollte sogar noch helfen. Hat leider nicht gereicht. 
Hat leider auch diesmal nicht gereicht für das Team Köln. Ballauf und Schenk sind einfach "drübber". Nicht mehr originell, nicht mehr witzig, nicht mehr ein tolles Team. Schaut euch mal Selb und Moormann aus Bremen an (Liebeswut bspw.) Da geht noch was. Da gibt es Charakter, witzige Dialoge ... Ballauf nimmt einem Schuldner die letzte zusammengekratzte Kohle ab mit dem lapidaren Hinweis: "Beweismittel" - ohne Handschuhe, ohne Asservaten-Tüte in die Jackeninnentasche, das ist doppelt armselig. Bitte aufhören.